name: figma
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: any
  http: any
  flutter_spinkit: any
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.2
  another_flushbar: ^1.12.30
  websafe_svg: any
  responsive_builder: ^0.7.0
  entry: ^0.0.8+1
  get: ^4.6.6
  image_picker: ^1.0.4



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/


  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
    - family: HindSiliguri
      # fonts:
      #    - asset: fonts/HindSiliguri-Regular.ttf
      #    - asset: fonts/HindSiliguri-Bold.ttf
      #    - asset: fonts/HindSiliguri-Light.ttf
      #    - asset: fonts/HindSiliguri-Medium.ttf
      #    - asset: fonts/HindSiliguri-SemiBold.ttf
  

